### ISSUE TITLE
Local deployment

### ISSUE THREAD

**Issue by bellaj** [chainstack/freedom-dividend-chaincode#19]
I am wondering if there is any guide to shift from Chainstacl to a locally deployed hyperledger.?

**Comment by akegaviar** [comment]
Hey @bellaj any reason for that? Our instructions for this piece are targeting specifically Chainstack deployments of Hyperledger Fabric as it's much easier to deploy, maintain etc.

**Comment by bellaj** [comment]
There is no specific reason.
I am helping some students to learn about hyperledger fabric. After using chainstack I wanted them to deploy a local network and reuse the same example.
